project_id = "ahcfusiarhxzvreuitvv"

[functions.create-promotion-payment]
verify_jwt = true

[functions.verify-promotion-payment]
verify_jwt = false

[functions.connect-stripe-account]
verify_jwt = true

[functions.create-booking-payment]
verify_jwt = true

[functions.verify-booking-payment]
verify_jwt = false

[functions.check-stripe-account]
verify_jwt = true

[functions.submit-quote-request]
verify_jwt = true

[functions.submit-quote-response]
verify_jwt = true
